### ISSUE TITLE
Packages in Ornithology

### ISSUE THREAD

**Issue by beausoleilmo** [DrMattG/REcol-verse#6]
[Here is a list](https://beausoleilmo.github.io/Ornithometrics-ctv/Ornithometrics.html) I've been building for ornithology. 

You might be interested in including some packages in this list. I'm still working on it... but if you have comments for mine, I'll take them :D. 

Hope this can help!

**Comment by DrMattG** [comment]
Wow - thanks so much. Your list is great. I added about 57 packages that I did not have before. I really like the idea of a Cran task view for Ornithology - perhaps one for ecology would be a step to far - although it would probably be very useful! (maybe a future colloboration?). Thanks again.

**Comment by beausoleilmo** [comment]
Awesome! I guess we have similar interest! Here is a task view that might interest you https://cran.r-project.org/web/views/Environmetrics.html. I think your list is more exhaustive!
